# Generated by Django 3.0.4 on 2020-03-04 16:55

from django.db import migrations


def seed(apps, schema_editor):
    Card = apps.get_model('flashcards', 'Card')
    Category = apps.get_model('flashcards', 'Category')

    javascript = Category(category="JavaScript")
    css = Category(category="CSS")
    reactjs = Category(category="ReactJS")
    frontend = Category(category="Front End")
    backend = Category(category="Back End")

    Card(category=javascript, question='What does a doctype do?',
         answer='Doctype stands for Document Type Declaration. It informs the web browser about the type and version of HTML used in building the web document. This helps the browser to handle and load it properly.',).save()
    Card(category=backend, question='What is Node.js? Where can you use it?',
         answer='Node.js is a server-side platform built on Google Chrome\'s JavaScript Engine(V8 Engine). Node.js is primarily used for non-blocking, event-driven servers, due to its single-threaded nature. It\'s used for traditional web sites and back-end API services, but was designed with real-time, push-based architectures in mind',).save()


def fallow(apps, schema_editor):
    Card = apps.get_model('flashcards', 'Card')
    Category = apps.get_model('flashcards', 'Category')
    Category.objects.all().delete()
    Card.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
