# Generated by Django 3.0.4 on 2020-03-04 19:29

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
