# Generated by Django 3.0.4 on 2020-03-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20200304_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(to='flashcards.Category'),
        ),
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(to='flashcards.Deck'),
        ),
    ]
