# Generated by Django 3.0.4 on 2020-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_auto_20200304_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='decks',
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', to='flashcards.Card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='flashcards.Category'),
        ),
    ]
