# Generated by Django 3.0.4 on 2020-03-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_auto_20200304_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default='Card Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(related_name='cards', to='flashcards.Category'),
        ),
    ]
